# Generated by Django 4.2 on 2023-04-11 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Studies',
            new_name='Marks',
        ),
    ]
