# Generated by Django 4.2 on 2023-04-12 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_branches'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Branches',
            new_name='Branch',
        ),
    ]
