# Generated by Django 4.2 on 2023-04-12 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_rename_code_branch_br_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.branch'),
        ),
    ]
